#pragma once
#define THEME_BOSS "Sounds/music/Boss_Battle_Poison_Mind.wav"
#define THEME_ENDGAME "Sounds/music/End_Game.wav"
#define THEME_GAMEOVER "Sounds/music/Game_Over.wav"
#define THEME_LIFELOST "Sounds/music/Life_Lost.wav"
#define THEME_STATE1 "Sounds/music/Stage_01.wav"
#define THEME_STATE4 "Sounds/music/Stage_04.wav"
#define THEME_STATECLEAR "Sounds/music/Stage_Clear.wav"

#define SOUND_EATITEM "Sounds/sound/collectitem.wav"
#define SOUND_EATWEAPON "Sounds/sound/collectweapon.wav"
#define SOUND_HIT "Sounds/sound/hit.wav"
#define SOUND_HITCANON "Sounds/sound/hitcannon.wav"
#define SOUND_OPENDOOR "Sounds/sound/opendoor.wav"
#define SOUND_SELECT "Sounds/sound/select.wav"
#define SOUND_WHIPATK "Sounds/sound/usingwhip.wav"
#define SOUND_CHEATE "Sounds/sound/minh.wav"
#define SOUND_AHH "Sounds/sound/aah.wav"
